### ISSUE TITLE
Travis failed in linux

### ISSUE THREAD

**Issue by sepandhaghighi** [ECSIM/gopem#13]
@mahi97 
Please check travis test in linux.
There is some problem in platform plugin `xcb`  and  `xvfb`.

**Comment by mahi97** [comment]
I fix `xcb` problem but now we have a problem with `dbus` and it seems to be a bug in PyQt5.

I suggest to postpone this issue for the next release and remove the Linux test for now.

As python is cross-platform and osx is POSIX systems too, I believe nothing will go wrong.

**Comment by sepandhaghighi** [comment]
Ok. We run static test(static_test.sh) in this version. I will fix travis config later.
Thanks for your efforts.

**Comment by sepandhaghighi** [comment]
fixed
