### ISSUE TITLE
Update docstrings

### ISSUE THREAD

**Issue by sepandhaghighi** [ECSIM/gopem#17]
Update docstrings of functions and methods

**Comment by mahi97** [comment]
Hi, could you please be more specific about this one?
Do you want me to docstring all the functions?

**Comment by sepandhaghighi** [comment]
Yeah, please add docstring to all functions ane methods.
Note : Use PyCharm template.

**Comment by mahi97** [comment]
Done #18

**Comment by sepandhaghighi** [comment]
@mahi97 Thanks for your efforts.
But your changes made a bug and `GOPEM` isn't working!!!
Please take a look ;-)

**Comment by sepandhaghighi** [comment]
fixed
