### ISSUE TITLE
file_name variable used out of its scope

### ISSUE THREAD

**Issue by mahi97** [ECSIM/gopem#19]
Dear @sepandhaghighi 
Please kindly check following lines of code again, the code-factor mentioned that file_name variable is used in a scope that it's not defined and I guess its right.

https://github.com/ECSIM/gopem/blob/842a709af1c470e3b294a2dd16d797a94f18d3c6/rsrc/version_check.py#L65

**Comment by sepandhaghighi** [comment]
@mahi97 
You were right, fixed ;-)
