### ISSUE TITLE
Migrating to GitHub Actions

### ISSUE THREAD

**Issue by sepandhaghighi** [ECSIM/gopem#86]
#### Description
Migrating from Travis/Appveyor to GitHub Actions

**Comment by sepandhaghighi** [comment]
@sadrasabouri Do you have any interest in this issue?

**Comment by sadrasabouri** [comment]
I think I don't have push permission to this repository. :disappointed:

**Comment by sepandhaghighi** [comment]
> I think I don't have push permission to this repository. 😞

Access granted 💯
